# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@sindresorhus/is-0.7.0" = {
      name = "_at_sindresorhus_slash_is";
      packageName = "@sindresorhus/is";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/is/-/is-0.7.0.tgz";
        sha512 = "ONhaKPIufzzrlNbqtWFFd+jlnemX6lJAgq9ZeiZtS7I1PIf/la7CW4m83rTXRnVnsMbW2k56pGYu7AUFJD9Pow==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "arch-2.1.1" = {
      name = "arch";
      packageName = "arch";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arch/-/arch-2.1.1.tgz";
        sha512 = "BLM56aPo9vLLFVa8+/+pJLnrZ7QGGTVHWsCwieAWT9o9K8UeGaQbzZbGoabWLOo2ksBCztoXdqBZBplqLDDCSg==";
      };
    };
    "archive-type-4.0.0" = {
      name = "archive-type";
      packageName = "archive-type";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archive-type/-/archive-type-4.0.0.tgz";
        sha1 = "f92e72233056dfc6969472749c267bdb046b1d70";
      };
    };
    "array-find-index-1.0.2" = {
      name = "array-find-index";
      packageName = "array-find-index";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-find-index/-/array-find-index-1.0.2.tgz";
        sha1 = "df010aa1287e164bbda6f9723b0a96a1ec4187a1";
      };
    };
    "base64-js-1.3.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz";
        sha512 = "mLQ4i2QO1ytvGWFWmcngKO//JXAQueZvwEKtjgQFM4jIK0kU+ytMfplL8j+n5mspOfjHwoAg+9yhb7BwAHm36g==";
      };
    };
    "bin-build-3.0.0" = {
      name = "bin-build";
      packageName = "bin-build";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bin-build/-/bin-build-3.0.0.tgz";
        sha512 = "jcUOof71/TNAI2uM5uoUaDq2ePcVBQ3R/qhxAz1rX7UfvduAL/RXD3jXzvn8cVcDJdGVkiR1shal3OH0ImpuhA==";
      };
    };
    "bin-check-4.1.0" = {
      name = "bin-check";
      packageName = "bin-check";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bin-check/-/bin-check-4.1.0.tgz";
        sha512 = "b6weQyEUKsDGFlACWSIOfveEnImkJyK/FGW6FAG42loyoquvjdtOIqO6yBFzHyqyVVhNgNkQxxx09SFLK28YnA==";
      };
    };
    "bin-version-3.1.0" = {
      name = "bin-version";
      packageName = "bin-version";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bin-version/-/bin-version-3.1.0.tgz";
        sha512 = "Mkfm4iE1VFt4xd4vH+gx+0/71esbfus2LsnCGe8Pi4mndSPyT+NGES/Eg99jx8/lUGWfu3z2yuB/bt5UB+iVbQ==";
      };
    };
    "bin-version-check-4.0.0" = {
      name = "bin-version-check";
      packageName = "bin-version-check";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bin-version-check/-/bin-version-check-4.0.0.tgz";
        sha512 = "sR631OrhC+1f8Cvs8WyVWOA33Y8tgwjETNPyyD/myRBXLkfS/vl74FmH/lFcRl9KY3zwGh7jFhvyk9vV3/3ilQ==";
      };
    };
    "bin-wrapper-4.1.0" = {
      name = "bin-wrapper";
      packageName = "bin-wrapper";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bin-wrapper/-/bin-wrapper-4.1.0.tgz";
        sha512 = "hfRmo7hWIXPkbpi0ZltboCMVrU+0ClXR/JgbCKKjlDjQf6igXa7OwdqNcFWQZPZTgiY7ZpzE3+LjjkLiTN2T7Q==";
      };
    };
    "bl-1.2.2" = {
      name = "bl";
      packageName = "bl";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.2.2.tgz";
        sha512 = "e8tQYnZodmebYDWGH7KMRvtzKXaJHx3BbilrgZCfvyLUYdKpK1t5PSPmpkny/SgiTSCnjfLW7v5rlONXVFkQEA==";
      };
    };
    "buffer-5.4.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.4.3.tgz";
        sha512 = "zvj65TkFeIt3i6aj5bIvJDzjjQQGs4o/sNoezg1F1kYap9Nu2jcUdpwzRSJTHMMzG0H7bZkn4rNQpImhuxWX2A==";
      };
    };
    "buffer-alloc-1.2.0" = {
      name = "buffer-alloc";
      packageName = "buffer-alloc";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc/-/buffer-alloc-1.2.0.tgz";
        sha512 = "CFsHQgjtW1UChdXgbyJGtnm+O/uLQeZdtbDo8mfUgYXCHSM1wgrVxXm6bSyrUuErEb+4sYVGCzASBRot7zyrow==";
      };
    };
    "buffer-alloc-unsafe-1.1.0" = {
      name = "buffer-alloc-unsafe";
      packageName = "buffer-alloc-unsafe";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc-unsafe/-/buffer-alloc-unsafe-1.1.0.tgz";
        sha512 = "TEM2iMIEQdJ2yjPJoSIsldnleVaAk1oW3DBVUykyOLsEsFmEc9kn+SFFPz+gl54KQNxlDnAwCXosOS9Okx2xAg==";
      };
    };
    "buffer-crc32-0.2.13" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.13.tgz";
        sha1 = "0d333e3f00eac50aa1454abd30ef8c2a5d9a7242";
      };
    };
    "buffer-fill-1.0.0" = {
      name = "buffer-fill";
      packageName = "buffer-fill";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-fill/-/buffer-fill-1.0.0.tgz";
        sha1 = "f8f78b76789888ef39f205cd637f68e702122b2c";
      };
    };
    "cacheable-request-2.1.4" = {
      name = "cacheable-request";
      packageName = "cacheable-request";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-request/-/cacheable-request-2.1.4.tgz";
        sha1 = "0d808801b6342ad33c91df9d0b44dc09b91e5c3d";
      };
    };
    "camelcase-2.1.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-2.1.1.tgz";
        sha1 = "7c1d16d679a1bbe59ca02cacecfb011e201f5a1f";
      };
    };
    "camelcase-keys-2.1.0" = {
      name = "camelcase-keys";
      packageName = "camelcase-keys";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase-keys/-/camelcase-keys-2.1.0.tgz";
        sha1 = "308beeaffdf28119051efa1d932213c91b8f92e7";
      };
    };
    "caw-2.0.1" = {
      name = "caw";
      packageName = "caw";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/caw/-/caw-2.0.1.tgz";
        sha512 = "Cg8/ZSBEa8ZVY9HspcGUYaK63d/bN7rqS3CYCzEGUxuYv6UlmcjzDUz2fCFFHyTvUW5Pk0I+3hkA3iXlIj6guA==";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "clone-response-1.0.2" = {
      name = "clone-response";
      packageName = "clone-response";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone-response/-/clone-response-1.0.2.tgz";
        sha1 = "d1dc973920314df67fbeb94223b4ee350239e96b";
      };
    };
    "commander-2.8.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.8.1.tgz";
        sha1 = "06be367febfda0c330aa1e2a072d3dc9762425d4";
      };
    };
    "config-chain-1.1.12" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.12.tgz";
        sha512 = "a1eOIcu8+7lUInge4Rpf/n4Krkf3Dd9lqhljRzII1/Zno/kRtUWnznPO3jOKBmTEktkt3fkxisUcivoj0ebzoA==";
      };
    };
    "console-stream-0.1.1" = {
      name = "console-stream";
      packageName = "console-stream";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-stream/-/console-stream-0.1.1.tgz";
        sha1 = "a095fe07b20465955f2fafd28b5d72bccd949d44";
      };
    };
    "content-disposition-0.5.3" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.3.tgz";
        sha512 = "ExO0774ikEObIAEV9kDo50o+79VCUdEB6n6lzKgGwupcVeRlhrj3qGAfwq8G6uBJjkqLrhT0qEYFcWng8z1z0g==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cross-spawn-5.1.0" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-5.1.0.tgz";
        sha1 = "e8bd0efee58fcff6f8f94510a0a554bbfa235449";
      };
    };
    "cross-spawn-6.0.5" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "6.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-6.0.5.tgz";
        sha512 = "eTVLrBSt7fjbDygz805pMnstIs2VTBNkRm0qxZd+M7A5XDdxVRWO5MxGBXZhjY4cqLYLdtrGqRf8mBPmzwSpWQ==";
      };
    };
    "currently-unhandled-0.4.1" = {
      name = "currently-unhandled";
      packageName = "currently-unhandled";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/currently-unhandled/-/currently-unhandled-0.4.1.tgz";
        sha1 = "988df33feab191ef799a61369dd76c17adf957ea";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "decompress-4.2.0" = {
      name = "decompress";
      packageName = "decompress";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress/-/decompress-4.2.0.tgz";
        sha1 = "7aedd85427e5a92dacfe55674a7c505e96d01f9d";
      };
    };
    "decompress-response-3.3.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-3.3.0.tgz";
        sha1 = "80a4dd323748384bfa248083622aedec982adff3";
      };
    };
    "decompress-tar-4.1.1" = {
      name = "decompress-tar";
      packageName = "decompress-tar";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-tar/-/decompress-tar-4.1.1.tgz";
        sha512 = "JdJMaCrGpB5fESVyxwpCx4Jdj2AagLmv3y58Qy4GE6HMVjWz1FeVQk1Ct4Kye7PftcdOo/7U7UKzYBJgqnGeUQ==";
      };
    };
    "decompress-tarbz2-4.1.1" = {
      name = "decompress-tarbz2";
      packageName = "decompress-tarbz2";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-tarbz2/-/decompress-tarbz2-4.1.1.tgz";
        sha512 = "s88xLzf1r81ICXLAVQVzaN6ZmX4A6U4z2nMbOwobxkLoIIfjVMBg7TeguTUXkKeXni795B6y5rnvDw7rxhAq9A==";
      };
    };
    "decompress-targz-4.1.1" = {
      name = "decompress-targz";
      packageName = "decompress-targz";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-targz/-/decompress-targz-4.1.1.tgz";
        sha512 = "4z81Znfr6chWnRDNfFNqLwPvm4db3WuZkqV+UgXQzSngG3CEKdBkw5jrv3axjjL96glyiiKjsxJG3X6WBZwX3w==";
      };
    };
    "decompress-unzip-4.0.1" = {
      name = "decompress-unzip";
      packageName = "decompress-unzip";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-unzip/-/decompress-unzip-4.0.1.tgz";
        sha1 = "deaaccdfd14aeaf85578f733ae8210f9b4848f69";
      };
    };
    "download-6.2.5" = {
      name = "download";
      packageName = "download";
      version = "6.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/download/-/download-6.2.5.tgz";
        sha512 = "DpO9K1sXAST8Cpzb7kmEhogJxymyVUd5qz/vCOSyvwtp2Klj2XcDt5YUuasgxka44SxF0q5RriKIwJmQHG2AuA==";
      };
    };
    "download-7.1.0" = {
      name = "download";
      packageName = "download";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/download/-/download-7.1.0.tgz";
        sha512 = "xqnBTVd/E+GxJVrX5/eUJiLYjCGPwMpdL+jGhGU57BvtcA7wwhtHVbXBeUk51kOpW3S7Jn3BQbN9Q1R1Km2qDQ==";
      };
    };
    "duplexer3-0.1.4" = {
      name = "duplexer3";
      packageName = "duplexer3";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer3/-/duplexer3-0.1.4.tgz";
        sha1 = "ee01dd1cac0ed3cbc7fdbea37dc0a8f1ce002ce2";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "execa-0.7.0" = {
      name = "execa";
      packageName = "execa";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-0.7.0.tgz";
        sha1 = "944becd34cc41ee32a63a9faf27ad5a65fc59777";
      };
    };
    "execa-1.0.0" = {
      name = "execa";
      packageName = "execa";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-1.0.0.tgz";
        sha512 = "adbxcyWV46qiHyvSp50TKt05tB4tK3HcmF7/nxfAdhnox83seTDbwnaqKO4sXRy7roHAIFqJP/Rw/AuEbX61LA==";
      };
    };
    "executable-4.1.1" = {
      name = "executable";
      packageName = "executable";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/executable/-/executable-4.1.1.tgz";
        sha512 = "8iA79xD3uAch729dUG8xaaBBFGaEa0wdD2VkYLFHwlqosEj/jT66AzcreRDSgV7ehnNLBW2WR5jIXwGKjVdTLg==";
      };
    };
    "ext-list-2.2.2" = {
      name = "ext-list";
      packageName = "ext-list";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ext-list/-/ext-list-2.2.2.tgz";
        sha512 = "u+SQgsubraE6zItfVA0tBuCBhfU9ogSRnsvygI7wht9TS510oLkBRXBsqopeUG/GBOIQyKZO9wjTqIu/sf5zFA==";
      };
    };
    "ext-name-5.0.0" = {
      name = "ext-name";
      packageName = "ext-name";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ext-name/-/ext-name-5.0.0.tgz";
        sha512 = "yblEwXAbGv1VQDmow7s38W77hzAgJAO50ztBLMcUyUBfxv1HC+LGwtiEN+Co6LtlqT/5uwVOxsD4TNIilWhwdQ==";
      };
    };
    "fd-slicer-1.1.0" = {
      name = "fd-slicer";
      packageName = "fd-slicer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fd-slicer/-/fd-slicer-1.1.0.tgz";
        sha1 = "25c7c89cb1f9077f8891bbe61d8f390eae256f1e";
      };
    };
    "figures-1.7.0" = {
      name = "figures";
      packageName = "figures";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-1.7.0.tgz";
        sha1 = "cbe1e3affcf1cd44b80cadfed28dc793a9701d2e";
      };
    };
    "file-type-3.9.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "3.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-3.9.0.tgz";
        sha1 = "257a078384d1db8087bc449d107d52a52672b9e9";
      };
    };
    "file-type-4.4.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-4.4.0.tgz";
        sha1 = "1b600e5fca1fbdc6e80c0a70c71c8dba5f7906c5";
      };
    };
    "file-type-5.2.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-5.2.0.tgz";
        sha1 = "2ddbea7c73ffe36368dfae49dc338c058c2b8ad6";
      };
    };
    "file-type-6.2.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-6.2.0.tgz";
        sha512 = "YPcTBDV+2Tm0VqjybVd32MHdlEGAtuxS3VAYsumFokDSMG+ROT5wawGlnHDoz7bfMcMDt9hxuXvXwoKUx2fkOg==";
      };
    };
    "file-type-8.1.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-8.1.0.tgz";
        sha512 = "qyQ0pzAy78gVoJsmYeNgl8uH8yKhr1lVhW7JbzJmnlRi0I4R2eEDEJZVKG8agpDnLpacwNbDhLNG/LMdxHD2YQ==";
      };
    };
    "filename-reserved-regex-2.0.0" = {
      name = "filename-reserved-regex";
      packageName = "filename-reserved-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filename-reserved-regex/-/filename-reserved-regex-2.0.0.tgz";
        sha1 = "abf73dfab735d045440abfea2d91f389ebbfa229";
      };
    };
    "filenamify-2.1.0" = {
      name = "filenamify";
      packageName = "filenamify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filenamify/-/filenamify-2.1.0.tgz";
        sha512 = "ICw7NTT6RsDp2rnYKVd8Fu4cr6ITzGy3+u4vUujPkabyaz+03F24NWEX7fs5fp+kBonlaqPH8fAO2NM+SXt/JA==";
      };
    };
    "find-up-1.1.2" = {
      name = "find-up";
      packageName = "find-up";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-1.1.2.tgz";
        sha1 = "6b2e9822b1a2ce0a60ab64d610eccad53cb24d0f";
      };
    };
    "find-versions-3.2.0" = {
      name = "find-versions";
      packageName = "find-versions";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-versions/-/find-versions-3.2.0.tgz";
        sha512 = "P8WRou2S+oe222TOCHitLy8zj+SIsVJh52VP4lvXkaFVnOFFdoWv1H1Jjvel1aI6NCFOAaeAVm8qrI0odiLcww==";
      };
    };
    "from2-2.3.0" = {
      name = "from2";
      packageName = "from2";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/from2/-/from2-2.3.0.tgz";
        sha1 = "8bfb5502bde4a4d36cfdeea007fcca21d7e382af";
      };
    };
    "fs-constants-1.0.0" = {
      name = "fs-constants";
      packageName = "fs-constants";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-constants/-/fs-constants-1.0.0.tgz";
        sha512 = "y6OAwoSIf7FyjMIv94u+b5rdheZEjzR63GTyZJm5qh4Bi+2YgwLCcI/fPFZkL5PSixOt6ZNKm+w+Hfp/Bciwow==";
      };
    };
    "get-proxy-2.1.0" = {
      name = "get-proxy";
      packageName = "get-proxy";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-proxy/-/get-proxy-2.1.0.tgz";
        sha512 = "zmZIaQTWnNQb4R4fJUEp/FC51eZsc6EkErspy3xtIYStaq8EB/hDIWipxsal+E8rz0qD7f2sL/NA9Xee4RInJw==";
      };
    };
    "get-stdin-4.0.1" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-4.0.1.tgz";
        sha1 = "b968c6b0a04384324902e8bf1a5df32579a450fe";
      };
    };
    "get-stream-2.3.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-2.3.1.tgz";
        sha1 = "5f38f93f346009666ee0150a054167f91bdd95de";
      };
    };
    "get-stream-3.0.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-3.0.0.tgz";
        sha1 = "8e943d1358dc37555054ecbe2edb05aa174ede14";
      };
    };
    "get-stream-4.1.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-4.1.0.tgz";
        sha512 = "GMat4EJ5161kIy2HevLlr4luNjBgvmj413KaQA7jt4V8B4RDsfpHk7WQ9GVqfYyyx8OS/L66Kox+rJRNklLK7w==";
      };
    };
    "got-7.1.0" = {
      name = "got";
      packageName = "got";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-7.1.0.tgz";
        sha512 = "Y5WMo7xKKq1muPsxD+KmrR8DH5auG7fBdDVueZwETwV6VytKyU9OX/ddpq2/1hp1vIPvVb4T81dKQz3BivkNLw==";
      };
    };
    "got-8.3.2" = {
      name = "got";
      packageName = "got";
      version = "8.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-8.3.2.tgz";
        sha512 = "qjUJ5U/hawxosMryILofZCkm3C84PLJS/0grRIpjAwu+Lkxxj5cxeCU25BG0/3mDSpXKTyZr8oh8wIgLaH0QCw==";
      };
    };
    "graceful-fs-4.2.3" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.3.tgz";
        sha512 = "a30VEBm4PEdx1dRB7MFK7BejejvCvBronbLjht+sHuGYj8PHs7M/5Z+rt5lw551vZ7yfTCj4Vuyy3mSJytDWRQ==";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-symbol-support-x-1.4.2" = {
      name = "has-symbol-support-x";
      packageName = "has-symbol-support-x";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbol-support-x/-/has-symbol-support-x-1.4.2.tgz";
        sha512 = "3ToOva++HaW+eCpgqZrCfN51IPB+7bJNVT6CUATzueB5Heb8o6Nam0V3HG5dlDvZU1Gn5QLcbahiKw/XVk5JJw==";
      };
    };
    "has-to-string-tag-x-1.4.1" = {
      name = "has-to-string-tag-x";
      packageName = "has-to-string-tag-x";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-to-string-tag-x/-/has-to-string-tag-x-1.4.1.tgz";
        sha512 = "vdbKfmw+3LoOYVr+mtxHaX5a96+0f3DljYd8JOqvOLsf5mw2Otda2qCDT9qRqLAhrjyQ0h7ual5nOiASpsGNFw==";
      };
    };
    "hosted-git-info-2.8.8" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.8.8.tgz";
        sha512 = "f/wzC2QaWBs7t9IYqB4T3sR1xviIViXJRJTWBlx2Gf3g0Xi5vI7Yy4koXQ1c9OYDGHN9sBy1DQ2AB8fqZBWhUg==";
      };
    };
    "http-cache-semantics-3.8.1" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "3.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-3.8.1.tgz";
        sha512 = "5ai2iksyV8ZXmnZhHH4rWPoxxistEexSi5936zIQ1bnNTW5VnA85B6P/VpXiRM017IgRvb2kKo1a//y+0wSp3w==";
      };
    };
    "ieee754-1.1.13" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.13.tgz";
        sha512 = "4vf7I2LYV/HaWerSo3XmlMkp5eZ83i+/CDluXi/IGTs/O1sejBNhTtnxzmRZfvOUqj7lZjqHkeTvpgSFDlWZTg==";
      };
    };
    "import-lazy-3.1.0" = {
      name = "import-lazy";
      packageName = "import-lazy";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-lazy/-/import-lazy-3.1.0.tgz";
        sha512 = "8/gvXvX2JMn0F+CDlSC4l6kOmVaLOO3XLkksI7CI3Ud95KDYJuYur2b9P/PUt/i/pDAMd/DulQsNbbbmRRsDIQ==";
      };
    };
    "indent-string-2.1.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-2.1.0.tgz";
        sha1 = "8e2d48348742121b4a8218b7a137e9a52049dc80";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.5" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.5.tgz";
        sha512 = "RZY5huIKCMRWDUqZlEi72f/lmXKMvuszcMBduliQ3nnWbx9X/ZBQO7DijMEYS9EhHBb2qacRUMtC7svLwe0lcw==";
      };
    };
    "into-stream-3.1.0" = {
      name = "into-stream";
      packageName = "into-stream";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/into-stream/-/into-stream-3.1.0.tgz";
        sha1 = "96fb0a936c12babd6ff1752a17d05616abd094c6";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-finite-1.1.0" = {
      name = "is-finite";
      packageName = "is-finite";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-finite/-/is-finite-1.1.0.tgz";
        sha512 = "cdyMtqX/BOqqNBBiKlIVkytNHm49MtMlYyn1zxzvJKWmFMlGzm+ry5BBfYyeY9YmNKbRSo/o7OX9w9ale0wg3w==";
      };
    };
    "is-natural-number-4.0.1" = {
      name = "is-natural-number";
      packageName = "is-natural-number";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-natural-number/-/is-natural-number-4.0.1.tgz";
        sha1 = "ab9d76e1db4ced51e35de0c72ebecf09f734cde8";
      };
    };
    "is-object-1.0.1" = {
      name = "is-object";
      packageName = "is-object";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-object/-/is-object-1.0.1.tgz";
        sha1 = "8952688c5ec2ffd6b03ecc85e769e02903083470";
      };
    };
    "is-plain-obj-1.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-1.1.0.tgz";
        sha1 = "71a50c8429dfca773c92a390a4a03b39fcd51d3e";
      };
    };
    "is-retry-allowed-1.2.0" = {
      name = "is-retry-allowed";
      packageName = "is-retry-allowed";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-retry-allowed/-/is-retry-allowed-1.2.0.tgz";
        sha512 = "RUbUeKwvm3XG2VYamhJL1xFktgjvPzL0Hq8C+6yrWIswDy3BIXGqCxhxkc30N9jqK311gVU137K8Ei55/zVJRg==";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "is-utf8-0.2.1" = {
      name = "is-utf8";
      packageName = "is-utf8";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-utf8/-/is-utf8-0.2.1.tgz";
        sha1 = "4b0da1442104d1b336340e80797e865cf39f7d72";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "isurl-1.0.0" = {
      name = "isurl";
      packageName = "isurl";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isurl/-/isurl-1.0.0.tgz";
        sha512 = "1P/yWsxPlDtn7QeRD+ULKQPaIaN6yF368GZ2vDfv0AL0NwpStafjWCDDdn0k8wgFMWpVAqG7oJhxHnlud42i9w==";
      };
    };
    "json-buffer-3.0.0" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.0.tgz";
        sha1 = "5b1f397afc75d677bde8bcfc0e47e1f9a3d9a898";
      };
    };
    "keyv-3.0.0" = {
      name = "keyv";
      packageName = "keyv";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-3.0.0.tgz";
        sha512 = "eguHnq22OE3uVoSYG0LVWNP+4ppamWr9+zWBe1bsNcovIMy6huUJFPgy4mGwCd/rnl3vOLGW1MTlu4c57CT1xA==";
      };
    };
    "load-json-file-1.1.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-1.1.0.tgz";
        sha1 = "956905708d58b4bab4c2261b04f59f31c99374c0";
      };
    };
    "logalot-2.1.0" = {
      name = "logalot";
      packageName = "logalot";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/logalot/-/logalot-2.1.0.tgz";
        sha1 = "5f8e8c90d304edf12530951a5554abb8c5e3f552";
      };
    };
    "longest-1.0.1" = {
      name = "longest";
      packageName = "longest";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/longest/-/longest-1.0.1.tgz";
        sha1 = "30a0b2da38f73770e8294a0d22e6625ed77d0097";
      };
    };
    "loud-rejection-1.6.0" = {
      name = "loud-rejection";
      packageName = "loud-rejection";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loud-rejection/-/loud-rejection-1.6.0.tgz";
        sha1 = "5b46f80147edee578870f086d04821cf998e551f";
      };
    };
    "lowercase-keys-1.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.0.tgz";
        sha1 = "4e3366b39e7f5457e35f1324bdf6f88d0bfc7306";
      };
    };
    "lowercase-keys-1.0.1" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.1.tgz";
        sha512 = "G2Lj61tXDnVFFOi8VZds+SoQjtQC3dgokKdDG2mTm1tx4m50NUHBOZSBwQQHyy0V12A0JTG4icfZQH+xPyh8VA==";
      };
    };
    "lpad-align-1.1.2" = {
      name = "lpad-align";
      packageName = "lpad-align";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lpad-align/-/lpad-align-1.1.2.tgz";
        sha1 = "21f600ac1c3095c3c6e497ee67271ee08481fe9e";
      };
    };
    "lru-cache-4.1.5" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.5.tgz";
        sha512 = "sWZlbEP2OsHNkXrMl5GYk/jKk70MBng6UU4YI/qGDYbgf6YbP4EvmqISbXCoJiRKs+1bSpFHVgQxvJ17F2li5g==";
      };
    };
    "make-dir-1.3.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-1.3.0.tgz";
        sha512 = "2w31R7SJtieJJnQtGc7RVL2StM2vGYVfqUOvUDxH6bC6aJTxPxTF0GnIgCyu7tjockiUWAYQRbxa7vKn34s5sQ==";
      };
    };
    "map-obj-1.0.1" = {
      name = "map-obj";
      packageName = "map-obj";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-obj/-/map-obj-1.0.1.tgz";
        sha1 = "d933ceb9205d82bdcf4886f6742bdc2b4dea146d";
      };
    };
    "meow-3.7.0" = {
      name = "meow";
      packageName = "meow";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/meow/-/meow-3.7.0.tgz";
        sha1 = "72cb668b425228290abbfa856892587308a801fb";
      };
    };
    "mime-db-1.43.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.43.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.43.0.tgz";
        sha512 = "+5dsGEEovYbT8UY9yD7eE4XTc4UwJ1jBYlgaQQF38ENsKR3wj/8q8RFZrF9WIZpB2V1ArTVFUva8sAul1NzRzQ==";
      };
    };
    "mimic-response-1.0.1" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-1.0.1.tgz";
        sha512 = "j5EctnkH7amfV/q5Hgmoal1g2QHFJRraOtmx0JpIqkxhBhI/lJSl1nMpQ45hVarwNETOoWEimndZ4QK0RHxuxQ==";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "nice-try-1.0.5" = {
      name = "nice-try";
      packageName = "nice-try";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nice-try/-/nice-try-1.0.5.tgz";
        sha512 = "1nh45deeb5olNY7eX82BkPO7SSxR5SSYJiPTrTdFUVYwAl8CKMA5N9PjTYkHiRjisVcxcQ1HXdLhx2qxxJzLNQ==";
      };
    };
    "normalize-package-data-2.5.0" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.5.0.tgz";
        sha512 = "/5CMN3T0R4XTj4DcGaexo+roZSdSFW/0AOOTROrjxzCG1wrWXEsGbRKevjlIL+ZDE4sZlJr5ED4YW0yqmkK+eA==";
      };
    };
    "normalize-url-2.0.1" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-2.0.1.tgz";
        sha512 = "D6MUW4K/VzoJ4rJ01JFKxDrtY1v9wrgzCX5f2qj/lzH1m/lW6MhUZFKerVsnyjOhOsYzI9Kqqak+10l4LvLpMw==";
      };
    };
    "npm-conf-1.1.3" = {
      name = "npm-conf";
      packageName = "npm-conf";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-conf/-/npm-conf-1.1.3.tgz";
        sha512 = "Yic4bZHJOt9RCFbRP3GgpqhScOY4HH3V2P8yBj6CeYq118Qr+BLXqT2JvpJ00mryLESpgOxf5XlFv4ZjXxLScw==";
      };
    };
    "npm-run-path-2.0.2" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-2.0.2.tgz";
        sha1 = "35a9232dfa35d7067b4cb2ddf2357b1871536c5f";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "os-filter-obj-2.0.0" = {
      name = "os-filter-obj";
      packageName = "os-filter-obj";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-filter-obj/-/os-filter-obj-2.0.0.tgz";
        sha512 = "uksVLsqG3pVdzzPvmAHpBK0wKxYItuzZr7SziusRPoz67tGV8rL1szZ6IdeUrbqLjGDwApBtN29eEE3IqGHOjg==";
      };
    };
    "p-cancelable-0.3.0" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-0.3.0.tgz";
        sha512 = "RVbZPLso8+jFeq1MfNvgXtCRED2raz/dKpacfTNxsx6pLEpEomM7gah6VeHSYV3+vo0OAi4MkArtQcWWXuQoyw==";
      };
    };
    "p-cancelable-0.4.1" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-0.4.1.tgz";
        sha512 = "HNa1A8LvB1kie7cERyy21VNeHb2CWJJYqyyC2o3klWFfMGlFmWv2Z7sFgZH8ZiaYL95ydToKTFVXgMV/Os0bBQ==";
      };
    };
    "p-event-1.3.0" = {
      name = "p-event";
      packageName = "p-event";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-event/-/p-event-1.3.0.tgz";
        sha1 = "8e6b4f4f65c72bc5b6fe28b75eda874f96a4a085";
      };
    };
    "p-event-2.3.1" = {
      name = "p-event";
      packageName = "p-event";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-event/-/p-event-2.3.1.tgz";
        sha512 = "NQCqOFhbpVTMX4qMe8PF8lbGtzZ+LCiN7pcNrb/413Na7+TRoe1xkKUzuWa/YEJdGQ0FvKtj35EEbDoVPO2kbA==";
      };
    };
    "p-finally-1.0.0" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha1 = "3fbcfb15b899a44123b34b6dcc18b724336a2cae";
      };
    };
    "p-is-promise-1.1.0" = {
      name = "p-is-promise";
      packageName = "p-is-promise";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-is-promise/-/p-is-promise-1.1.0.tgz";
        sha1 = "9c9456989e9f6588017b0434d56097675c3da05e";
      };
    };
    "p-map-series-1.0.0" = {
      name = "p-map-series";
      packageName = "p-map-series";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-map-series/-/p-map-series-1.0.0.tgz";
        sha1 = "bf98fe575705658a9e1351befb85ae4c1f07bdca";
      };
    };
    "p-reduce-1.0.0" = {
      name = "p-reduce";
      packageName = "p-reduce";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-reduce/-/p-reduce-1.0.0.tgz";
        sha1 = "18c2b0dd936a4690a529f8231f58a0fdb6a47dfa";
      };
    };
    "p-timeout-1.2.1" = {
      name = "p-timeout";
      packageName = "p-timeout";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-timeout/-/p-timeout-1.2.1.tgz";
        sha1 = "5eb3b353b7fce99f101a1038880bb054ebbea386";
      };
    };
    "p-timeout-2.0.1" = {
      name = "p-timeout";
      packageName = "p-timeout";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-timeout/-/p-timeout-2.0.1.tgz";
        sha512 = "88em58dDVB/KzPEx1X0N3LwFfYZPyDc4B6eF38M1rk9VTZMbxXXgjugz8mmwpS9Ox4BDZ+t6t3QP5+/gazweIA==";
      };
    };
    "parse-json-2.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-2.2.0.tgz";
        sha1 = "f480f40434ef80741f8469099f8dea18f55a4dc9";
      };
    };
    "path-exists-2.1.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-2.1.0.tgz";
        sha1 = "0feb6c64f0fc518d9a754dd5efb62c7022761f4b";
      };
    };
    "path-key-2.0.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-2.0.1.tgz";
        sha1 = "411cadb574c5a140d3a4b1910d40d80cc9f40b40";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-type-1.1.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-1.1.0.tgz";
        sha1 = "59c44f7ee491da704da415da5a4070ba4f8fe441";
      };
    };
    "pend-1.2.0" = {
      name = "pend";
      packageName = "pend";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pend/-/pend-1.2.0.tgz";
        sha1 = "7a57eb550a6783f9115331fcf4663d5c8e007a50";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "pify-3.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-3.0.0.tgz";
        sha1 = "e5a4acd2c101fdf3d9a4d07f0dbc4db49dd28176";
      };
    };
    "pify-4.0.1" = {
      name = "pify";
      packageName = "pify";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-4.0.1.tgz";
        sha512 = "uB80kBFb/tfd68bVleG9T5GGsGPjJrLAUpR5PZIrhBnIaRTQRjqdJSsIKkOP6OAIFbj7GOrcudc5pNjZ+geV2g==";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "prepend-http-1.0.4" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz";
        sha1 = "d4f4562b0ce3696e41ac52d0e002e57a635dc6dc";
      };
    };
    "prepend-http-2.0.0" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-2.0.0.tgz";
        sha1 = "e92434bfa5ea8c19f41cdfd401d741a3c819d897";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha1 = "212d5bfe1318306a420f6402b8e26ff39647a849";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "query-string-5.1.1" = {
      name = "query-string";
      packageName = "query-string";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/query-string/-/query-string-5.1.1.tgz";
        sha512 = "gjWOsm2SoGlgLEdAGt7a6slVOk9mGiXmPFMqrEhLQ68rhQuBnpfs3+EmlvqKyxnCo9/PPlF+9MtY02S1aFg+Jw==";
      };
    };
    "read-pkg-1.1.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-1.1.0.tgz";
        sha1 = "f5ffaa5ecd29cb31c0474bca7d756b6bb29e3f28";
      };
    };
    "read-pkg-up-1.0.1" = {
      name = "read-pkg-up";
      packageName = "read-pkg-up";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-1.0.1.tgz";
        sha1 = "9d63c13276c065918d57f002a57f40a1b643fb02";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "redent-1.0.0" = {
      name = "redent";
      packageName = "redent";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redent/-/redent-1.0.0.tgz";
        sha1 = "cf916ab1fd5f1f16dfb20822dd6ec7f730c2afde";
      };
    };
    "repeating-2.0.1" = {
      name = "repeating";
      packageName = "repeating";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeating/-/repeating-2.0.1.tgz";
        sha1 = "5214c53a926d3552707527fbab415dbc08d06dda";
      };
    };
    "resolve-1.15.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.15.1.tgz";
        sha512 = "84oo6ZTtoTUpjgNEr5SJyzQhzL72gaRodsSfyxC/AXRvwu0Yse9H8eF9IpGo7b8YetZhlI6v7ZQ6bKBFV/6S7w==";
      };
    };
    "responselike-1.0.2" = {
      name = "responselike";
      packageName = "responselike";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-1.0.2.tgz";
        sha1 = "918720ef3b631c5642be068f15ade5a46f4ba1e7";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.0" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.0.tgz";
        sha512 = "fZEwUGbVl7kouZs1jCdMLdt95hdIv0ZeHg6L7qPeciMZhZ+/gdesW4wgTARkrFWEpspjEATAzUGPG8N2jJiwbg==";
      };
    };
    "seek-bzip-1.0.5" = {
      name = "seek-bzip";
      packageName = "seek-bzip";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/seek-bzip/-/seek-bzip-1.0.5.tgz";
        sha1 = "cfe917cb3d274bcffac792758af53173eb1fabdc";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "semver-regex-2.0.0" = {
      name = "semver-regex";
      packageName = "semver-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-regex/-/semver-regex-2.0.0.tgz";
        sha512 = "mUdIBBvdn0PLOeP3TEkMH7HHeUP3GjsXCwKarjv/kGmUFOYg1VqEemKhoQpWMu6X2I8kHeuVdGibLGkVK+/5Qw==";
      };
    };
    "semver-truncate-1.1.2" = {
      name = "semver-truncate";
      packageName = "semver-truncate";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-truncate/-/semver-truncate-1.1.2.tgz";
        sha1 = "57f41de69707a62709a7e0104ba2117109ea47e8";
      };
    };
    "shebang-command-1.2.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha1 = "44aac65b695b03398968c39f363fee5deafdf1ea";
      };
    };
    "shebang-regex-1.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha1 = "da42f49740c0b42db2ca9728571cb190c98efea3";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "sort-keys-1.1.2" = {
      name = "sort-keys";
      packageName = "sort-keys";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sort-keys/-/sort-keys-1.1.2.tgz";
        sha1 = "441b6d4d346798f1b4e49e8920adfba0e543f9ad";
      };
    };
    "sort-keys-2.0.0" = {
      name = "sort-keys";
      packageName = "sort-keys";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sort-keys/-/sort-keys-2.0.0.tgz";
        sha1 = "658535584861ec97d730d6cf41822e1f56684128";
      };
    };
    "sort-keys-length-1.0.1" = {
      name = "sort-keys-length";
      packageName = "sort-keys-length";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sort-keys-length/-/sort-keys-length-1.0.1.tgz";
        sha1 = "9cb6f4f4e9e48155a6aa0671edd336ff1479a188";
      };
    };
    "spdx-correct-3.1.0" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.1.0.tgz";
        sha512 = "lr2EZCctC2BNR7j7WzJ2FpDznxky1sjfxvvYEyzxNyb6lZXHODmEoJeFu4JupYlkfha1KZpJyoqiJ7pgA1qq8Q==";
      };
    };
    "spdx-exceptions-2.2.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.2.0.tgz";
        sha512 = "2XQACfElKi9SlVb1CYadKDXvoajPgBVPn/gOQLrTvHdElaVhr7ZEbqJaRnJLVNeaI4cMEAgVCeBMKF6MWRDCRA==";
      };
    };
    "spdx-expression-parse-3.0.0" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-3.0.0.tgz";
        sha512 = "Yg6D3XpRD4kkOmTpdgbUiEJFKghJH03fiC1OPll5h/0sO6neh2jqRDVHOQ4o/LMea0tgCkbMgea5ip/e+MkWyg==";
      };
    };
    "spdx-license-ids-3.0.5" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.5.tgz";
        sha512 = "J+FWzZoynJEXGphVIS+XEh3kFSjZX/1i9gFBaWQcB+/tmpe2qUsSBABpcxqxnAxFdiUFEgAX1bjYGQvIZmoz9Q==";
      };
    };
    "squeak-1.3.0" = {
      name = "squeak";
      packageName = "squeak";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/squeak/-/squeak-1.3.0.tgz";
        sha1 = "33045037b64388b567674b84322a6521073916c3";
      };
    };
    "strict-uri-encode-1.1.0" = {
      name = "strict-uri-encode";
      packageName = "strict-uri-encode";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-1.1.0.tgz";
        sha1 = "279b225df1d582b1f54e65addd4352e18faa0713";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "strip-bom-2.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz";
        sha1 = "6219a85616520491f35788bdbf1447a99c7e6b0e";
      };
    };
    "strip-dirs-2.1.0" = {
      name = "strip-dirs";
      packageName = "strip-dirs";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-dirs/-/strip-dirs-2.1.0.tgz";
        sha512 = "JOCxOeKLm2CAS73y/U4ZeZPTkE+gNVCzKt7Eox84Iej1LT/2pTWYpZKJuxwQpvX1LiZb1xokNR7RLfuBAa7T3g==";
      };
    };
    "strip-eof-1.0.0" = {
      name = "strip-eof";
      packageName = "strip-eof";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-eof/-/strip-eof-1.0.0.tgz";
        sha1 = "bb43ff5598a6eb05d89b59fcd129c983313606bf";
      };
    };
    "strip-indent-1.0.1" = {
      name = "strip-indent";
      packageName = "strip-indent";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-indent/-/strip-indent-1.0.1.tgz";
        sha1 = "0c7962a6adefa7bbd4ac366460a638552ae1a0a2";
      };
    };
    "strip-outer-1.0.1" = {
      name = "strip-outer";
      packageName = "strip-outer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-outer/-/strip-outer-1.0.1.tgz";
        sha512 = "k55yxKHwaXnpYGsOzg4Vl8+tDrWylxDEpknGjhTiZB8dFRU5rTo9CAzeycivxV3s+zlTKwrs6WxMxR95n26kwg==";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "tar-stream-1.6.2" = {
      name = "tar-stream";
      packageName = "tar-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-stream/-/tar-stream-1.6.2.tgz";
        sha512 = "rzS0heiNf8Xn7/mpdSVVSMAWAoy9bfb1WOTYC78Z0UQKeKa/CWS8FOq0lKGNa8DWKAn9gxjCvMLYc5PGXYlK2A==";
      };
    };
    "temp-dir-1.0.0" = {
      name = "temp-dir";
      packageName = "temp-dir";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/temp-dir/-/temp-dir-1.0.0.tgz";
        sha1 = "0a7c0ea26d3a39afa7e0ebea9c1fc0bc4daa011d";
      };
    };
    "tempfile-2.0.0" = {
      name = "tempfile";
      packageName = "tempfile";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tempfile/-/tempfile-2.0.0.tgz";
        sha1 = "6b0446856a9b1114d1856ffcbe509cccb0977265";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "timed-out-4.0.1" = {
      name = "timed-out";
      packageName = "timed-out";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/timed-out/-/timed-out-4.0.1.tgz";
        sha1 = "f32eacac5a175bea25d7fab565ab3ed8741ef56f";
      };
    };
    "to-buffer-1.1.1" = {
      name = "to-buffer";
      packageName = "to-buffer";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-buffer/-/to-buffer-1.1.1.tgz";
        sha512 = "lx9B5iv7msuFYE3dytT+KE5tap+rNYw+K4jVkb9R/asAb+pbBSM17jtunHplhBe6RRJdZx3Pn2Jph24O32mOVg==";
      };
    };
    "trim-newlines-1.0.0" = {
      name = "trim-newlines";
      packageName = "trim-newlines";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-newlines/-/trim-newlines-1.0.0.tgz";
        sha1 = "5887966bb582a4503a41eb524f7d35011815a613";
      };
    };
    "trim-repeated-1.0.0" = {
      name = "trim-repeated";
      packageName = "trim-repeated";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-repeated/-/trim-repeated-1.0.0.tgz";
        sha1 = "e3646a2ea4e891312bf7eace6cfb05380bc01c21";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "unbzip2-stream-1.3.3" = {
      name = "unbzip2-stream";
      packageName = "unbzip2-stream";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unbzip2-stream/-/unbzip2-stream-1.3.3.tgz";
        sha512 = "fUlAF7U9Ah1Q6EieQ4x4zLNejrRvDWUYmxXUpN3uziFYCHapjWFaCAnreY9bGgxzaMCFAPPpYNng57CypwJVhg==";
      };
    };
    "url-parse-lax-1.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-1.0.0.tgz";
        sha1 = "7af8f303645e9bd79a272e7a14ac68bc0609da73";
      };
    };
    "url-parse-lax-3.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-3.0.0.tgz";
        sha1 = "16b5cafc07dbe3676c1b1999177823d6503acb0c";
      };
    };
    "url-to-options-1.0.1" = {
      name = "url-to-options";
      packageName = "url-to-options";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-to-options/-/url-to-options-1.0.1.tgz";
        sha1 = "1505a03a289a48cbd7a434efbaeec5055f5633a9";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "validate-npm-package-license-3.0.4" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.4.tgz";
        sha512 = "DpKm2Ui/xN7/HQKCtpZxoRWBhZ9Z0kqtygG8XCgNQ8ZlDnxuQmWhj566j8fN4Cu3/JmbhsDo7fcAJq4s9h27Ew==";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "yauzl-2.10.0" = {
      name = "yauzl";
      packageName = "yauzl";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yauzl/-/yauzl-2.10.0.tgz";
        sha1 = "c7eb17c93e112cb1086fa6d8e51fb0667b79a5f9";
      };
    };
  };
  args = {
    name = "gifsicle";
    packageName = "gifsicle";
    version = "4.0.1";
    src = ./.;
    dependencies = [
      sources."@sindresorhus/is-0.7.0"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."arch-2.1.1"
      (sources."archive-type-4.0.0" // {
        dependencies = [
          sources."file-type-4.4.0"
        ];
      })
      sources."array-find-index-1.0.2"
      sources."base64-js-1.3.1"
      (sources."bin-build-3.0.0" // {
        dependencies = [
          sources."execa-0.7.0"
          sources."get-stream-3.0.0"
        ];
      })
      (sources."bin-check-4.1.0" // {
        dependencies = [
          sources."execa-0.7.0"
          sources."get-stream-3.0.0"
        ];
      })
      sources."bin-version-3.1.0"
      sources."bin-version-check-4.0.0"
      (sources."bin-wrapper-4.1.0" // {
        dependencies = [
          (sources."download-7.1.0" // {
            dependencies = [
              sources."pify-3.0.0"
            ];
          })
          sources."file-type-8.1.0"
          sources."get-stream-3.0.0"
          (sources."got-8.3.2" // {
            dependencies = [
              sources."pify-3.0.0"
            ];
          })
          sources."p-cancelable-0.4.1"
          sources."p-event-2.3.1"
          sources."p-timeout-2.0.1"
          sources."pify-4.0.1"
          sources."prepend-http-2.0.0"
          sources."url-parse-lax-3.0.0"
        ];
      })
      sources."bl-1.2.2"
      sources."buffer-5.4.3"
      sources."buffer-alloc-1.2.0"
      sources."buffer-alloc-unsafe-1.1.0"
      sources."buffer-crc32-0.2.13"
      sources."buffer-fill-1.0.0"
      (sources."cacheable-request-2.1.4" // {
        dependencies = [
          sources."get-stream-3.0.0"
          sources."lowercase-keys-1.0.0"
        ];
      })
      sources."camelcase-2.1.1"
      sources."camelcase-keys-2.1.0"
      sources."caw-2.0.1"
      sources."chalk-1.1.3"
      sources."clone-response-1.0.2"
      sources."commander-2.8.1"
      sources."config-chain-1.1.12"
      sources."console-stream-0.1.1"
      (sources."content-disposition-0.5.3" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."core-util-is-1.0.2"
      sources."cross-spawn-5.1.0"
      sources."currently-unhandled-0.4.1"
      sources."decamelize-1.2.0"
      sources."decode-uri-component-0.2.0"
      sources."decompress-4.2.0"
      sources."decompress-response-3.3.0"
      sources."decompress-tar-4.1.1"
      (sources."decompress-tarbz2-4.1.1" // {
        dependencies = [
          sources."file-type-6.2.0"
        ];
      })
      sources."decompress-targz-4.1.1"
      (sources."decompress-unzip-4.0.1" // {
        dependencies = [
          sources."file-type-3.9.0"
        ];
      })
      (sources."download-6.2.5" // {
        dependencies = [
          sources."get-stream-3.0.0"
          sources."pify-3.0.0"
        ];
      })
      sources."duplexer3-0.1.4"
      sources."end-of-stream-1.4.4"
      sources."error-ex-1.3.2"
      sources."escape-string-regexp-1.0.5"
      (sources."execa-1.0.0" // {
        dependencies = [
          sources."cross-spawn-6.0.5"
          sources."get-stream-4.1.0"
        ];
      })
      sources."executable-4.1.1"
      sources."ext-list-2.2.2"
      sources."ext-name-5.0.0"
      sources."fd-slicer-1.1.0"
      sources."figures-1.7.0"
      sources."file-type-5.2.0"
      sources."filename-reserved-regex-2.0.0"
      sources."filenamify-2.1.0"
      sources."find-up-1.1.2"
      sources."find-versions-3.2.0"
      sources."from2-2.3.0"
      sources."fs-constants-1.0.0"
      sources."get-proxy-2.1.0"
      sources."get-stdin-4.0.1"
      sources."get-stream-2.3.1"
      (sources."got-7.1.0" // {
        dependencies = [
          sources."get-stream-3.0.0"
        ];
      })
      sources."graceful-fs-4.2.3"
      sources."graceful-readlink-1.0.1"
      sources."has-ansi-2.0.0"
      sources."has-symbol-support-x-1.4.2"
      sources."has-to-string-tag-x-1.4.1"
      sources."hosted-git-info-2.8.8"
      sources."http-cache-semantics-3.8.1"
      sources."ieee754-1.1.13"
      sources."import-lazy-3.1.0"
      sources."indent-string-2.1.0"
      sources."inherits-2.0.4"
      sources."ini-1.3.5"
      sources."into-stream-3.1.0"
      sources."is-arrayish-0.2.1"
      sources."is-finite-1.1.0"
      sources."is-natural-number-4.0.1"
      sources."is-object-1.0.1"
      sources."is-plain-obj-1.1.0"
      sources."is-retry-allowed-1.2.0"
      sources."is-stream-1.1.0"
      sources."is-utf8-0.2.1"
      sources."isarray-1.0.0"
      sources."isexe-2.0.0"
      sources."isurl-1.0.0"
      sources."json-buffer-3.0.0"
      sources."keyv-3.0.0"
      sources."load-json-file-1.1.0"
      sources."logalot-2.1.0"
      sources."longest-1.0.1"
      sources."loud-rejection-1.6.0"
      sources."lowercase-keys-1.0.1"
      sources."lpad-align-1.1.2"
      sources."lru-cache-4.1.5"
      (sources."make-dir-1.3.0" // {
        dependencies = [
          sources."pify-3.0.0"
        ];
      })
      sources."map-obj-1.0.1"
      sources."meow-3.7.0"
      sources."mime-db-1.43.0"
      sources."mimic-response-1.0.1"
      sources."minimist-1.2.0"
      sources."nice-try-1.0.5"
      sources."normalize-package-data-2.5.0"
      (sources."normalize-url-2.0.1" // {
        dependencies = [
          sources."prepend-http-2.0.0"
          sources."sort-keys-2.0.0"
        ];
      })
      (sources."npm-conf-1.1.3" // {
        dependencies = [
          sources."pify-3.0.0"
        ];
      })
      sources."npm-run-path-2.0.2"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."os-filter-obj-2.0.0"
      sources."p-cancelable-0.3.0"
      sources."p-event-1.3.0"
      sources."p-finally-1.0.0"
      sources."p-is-promise-1.1.0"
      sources."p-map-series-1.0.0"
      sources."p-reduce-1.0.0"
      sources."p-timeout-1.2.1"
      sources."parse-json-2.2.0"
      sources."path-exists-2.1.0"
      sources."path-key-2.0.1"
      sources."path-parse-1.0.6"
      sources."path-type-1.1.0"
      sources."pend-1.2.0"
      sources."pify-2.3.0"
      sources."pinkie-2.0.4"
      sources."pinkie-promise-2.0.1"
      sources."prepend-http-1.0.4"
      sources."process-nextick-args-2.0.1"
      sources."proto-list-1.2.4"
      sources."pseudomap-1.0.2"
      sources."pump-3.0.0"
      sources."query-string-5.1.1"
      sources."read-pkg-1.1.0"
      sources."read-pkg-up-1.0.1"
      (sources."readable-stream-2.3.7" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."redent-1.0.0"
      sources."repeating-2.0.1"
      sources."resolve-1.15.1"
      sources."responselike-1.0.2"
      sources."safe-buffer-5.2.0"
      sources."seek-bzip-1.0.5"
      sources."semver-5.7.1"
      sources."semver-regex-2.0.0"
      sources."semver-truncate-1.1.2"
      sources."shebang-command-1.2.0"
      sources."shebang-regex-1.0.0"
      sources."signal-exit-3.0.2"
      sources."sort-keys-1.1.2"
      sources."sort-keys-length-1.0.1"
      sources."spdx-correct-3.1.0"
      sources."spdx-exceptions-2.2.0"
      sources."spdx-expression-parse-3.0.0"
      sources."spdx-license-ids-3.0.5"
      sources."squeak-1.3.0"
      sources."strict-uri-encode-1.1.0"
      (sources."string_decoder-1.1.1" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."strip-ansi-3.0.1"
      sources."strip-bom-2.0.0"
      sources."strip-dirs-2.1.0"
      sources."strip-eof-1.0.0"
      sources."strip-indent-1.0.1"
      sources."strip-outer-1.0.1"
      sources."supports-color-2.0.0"
      sources."tar-stream-1.6.2"
      sources."temp-dir-1.0.0"
      sources."tempfile-2.0.0"
      sources."through-2.3.8"
      sources."timed-out-4.0.1"
      sources."to-buffer-1.1.1"
      sources."trim-newlines-1.0.0"
      sources."trim-repeated-1.0.0"
      sources."tunnel-agent-0.6.0"
      sources."unbzip2-stream-1.3.3"
      sources."url-parse-lax-1.0.0"
      sources."url-to-options-1.0.1"
      sources."util-deprecate-1.0.2"
      sources."uuid-3.4.0"
      sources."validate-npm-package-license-3.0.4"
      sources."which-1.3.1"
      sources."wrappy-1.0.2"
      sources."xtend-4.0.2"
      sources."yallist-2.1.2"
      sources."yauzl-2.10.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "gifsicle wrapper that makes it seamlessly available as a local dependency";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}