# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@babel/code-frame-7.8.3" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.8.3.tgz";
        sha512 = "a9gxpmdXtZEInkCSHUJDLHZVBgb1QS0jhss4cPP93EW7s+uC5bikET2twEF3KV+7rDblJcmNvTR7VJejqd2C2g==";
      };
    };
    "@babel/helper-module-imports-7.8.3" = {
      name = "_at_babel_slash_helper-module-imports";
      packageName = "@babel/helper-module-imports";
      version = "7.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.8.3.tgz";
        sha512 = "R0Bx3jippsbAEtzkpZ/6FIiuzOURPcMjHp+Z6xPe6DtApDJx+w7UYyOLanZqO8+wKR9G10s/FmHXvxaMd9s6Kg==";
      };
    };
    "@babel/highlight-7.8.3" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.8.3.tgz";
        sha512 = "PX4y5xQUvy0fnEVHrYOarRPXVWafSjTW9T0Hab8gVIawpl2Sj0ORyrygANq+KjcNlSSTw0YCLSNA8OyZ1I4yEg==";
      };
    };
    "@babel/runtime-7.8.7" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.8.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.8.7.tgz";
        sha512 = "+AATMUFppJDw6aiR5NVPHqIQBlV/Pj8wY/EZH+lmvRdUo9xBaz/rF3alAwFJQavvKfeOlPE7oaaDHVbcySbCsg==";
      };
    };
    "@babel/types-7.8.7" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.8.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.8.7.tgz";
        sha512 = "k2TreEHxFA4CjGkL+GYjRyx35W0Mr7DP5+9q6WMkyKXB+904bYmG40syjMFV0oLlhhFCwWl0vA0DyzTDkwAiJw==";
      };
    };
    "@emotion/cache-10.0.29" = {
      name = "_at_emotion_slash_cache";
      packageName = "@emotion/cache";
      version = "10.0.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/cache/-/cache-10.0.29.tgz";
        sha512 = "fU2VtSVlHiF27empSbxi1O2JFdNWZO+2NFHfwO0pxgTep6Xa3uGb+3pVKfLww2l/IBGLNEZl5Xf/++A4wAYDYQ==";
      };
    };
    "@emotion/core-10.0.28" = {
      name = "_at_emotion_slash_core";
      packageName = "@emotion/core";
      version = "10.0.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/core/-/core-10.0.28.tgz";
        sha512 = "pH8UueKYO5jgg0Iq+AmCLxBsvuGtvlmiDCOuv8fGNYn3cowFpLN98L8zO56U0H1PjDIyAlXymgL3Wu7u7v6hbA==";
      };
    };
    "@emotion/css-10.0.27" = {
      name = "_at_emotion_slash_css";
      packageName = "@emotion/css";
      version = "10.0.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/css/-/css-10.0.27.tgz";
        sha512 = "6wZjsvYeBhyZQYNrGoR5yPMYbMBNEnanDrqmsqS1mzDm1cOTu12shvl2j4QHNS36UaTE0USIJawCH9C8oW34Zw==";
      };
    };
    "@emotion/hash-0.8.0" = {
      name = "_at_emotion_slash_hash";
      packageName = "@emotion/hash";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/hash/-/hash-0.8.0.tgz";
        sha512 = "kBJtf7PH6aWwZ6fka3zQ0p6SBYzx4fl1LoZXE2RrnYST9Xljm7WfKJrU4g/Xr3Beg72MLrp1AWNUmuYJTL7Cow==";
      };
    };
    "@emotion/is-prop-valid-0.8.7" = {
      name = "_at_emotion_slash_is-prop-valid";
      packageName = "@emotion/is-prop-valid";
      version = "0.8.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/is-prop-valid/-/is-prop-valid-0.8.7.tgz";
        sha512 = "OPkKzUeiid0vEKjZqnGcy2mzxjIlCffin+L2C02pdz/bVlt5zZZE2VzO0D3XOPnH0NEeF21QNKSXiZphjr4xiQ==";
      };
    };
    "@emotion/memoize-0.7.4" = {
      name = "_at_emotion_slash_memoize";
      packageName = "@emotion/memoize";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/memoize/-/memoize-0.7.4.tgz";
        sha512 = "Ja/Vfqe3HpuzRsG1oBtWTHk2PGZ7GR+2Vz5iYGelAw8dx32K0y7PjVuxK6z1nMpZOqAFsRUPCkK1YjJ56qJlgw==";
      };
    };
    "@emotion/serialize-0.11.16" = {
      name = "_at_emotion_slash_serialize";
      packageName = "@emotion/serialize";
      version = "0.11.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/serialize/-/serialize-0.11.16.tgz";
        sha512 = "G3J4o8by0VRrO+PFeSc3js2myYNOXVJ3Ya+RGVxnshRYgsvErfAOglKAiy1Eo1vhzxqtUvjCyS5gtewzkmvSSg==";
      };
    };
    "@emotion/sheet-0.9.4" = {
      name = "_at_emotion_slash_sheet";
      packageName = "@emotion/sheet";
      version = "0.9.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/sheet/-/sheet-0.9.4.tgz";
        sha512 = "zM9PFmgVSqBw4zL101Q0HrBVTGmpAxFZH/pYx/cjJT5advXguvcgjHFTCaIO3enL/xr89vK2bh0Mfyj9aa0ANA==";
      };
    };
    "@emotion/styled-10.0.27" = {
      name = "_at_emotion_slash_styled";
      packageName = "@emotion/styled";
      version = "10.0.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/styled/-/styled-10.0.27.tgz";
        sha512 = "iK/8Sh7+NLJzyp9a5+vIQIXTYxfT4yB/OJbjzQanB2RZpvmzBQOHZWhpAMZWYEKRNNbsD6WfBw5sVWkb6WzS/Q==";
      };
    };
    "@emotion/styled-base-10.0.28" = {
      name = "_at_emotion_slash_styled-base";
      packageName = "@emotion/styled-base";
      version = "10.0.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/styled-base/-/styled-base-10.0.28.tgz";
        sha512 = "bLYVsPlFZ3SIR9YQsuFiJ9mML76ZLnsAfbkwBFbdMTCJ/0I+xgv+SG/QYHiLvGUUohjNVPeneYUyTUkcKndWxg==";
      };
    };
    "@emotion/stylis-0.8.5" = {
      name = "_at_emotion_slash_stylis";
      packageName = "@emotion/stylis";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/stylis/-/stylis-0.8.5.tgz";
        sha512 = "h6KtPihKFn3T9fuIrwvXXUOwlx3rfUvfZIcP5a6rh8Y7zjE3O06hT5Ss4S/YI1AYhuZ1kjaE/5EaOOI2NqSylQ==";
      };
    };
    "@emotion/unitless-0.7.5" = {
      name = "_at_emotion_slash_unitless";
      packageName = "@emotion/unitless";
      version = "0.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/unitless/-/unitless-0.7.5.tgz";
        sha512 = "OWORNpfjMsSSUBVrRBVGECkhWcULOAJz9ZW8uK9qgxD+87M7jHRcvh/A96XXNhXTLmKcoYSQtBEX7lHMO7YRwg==";
      };
    };
    "@emotion/utils-0.11.3" = {
      name = "_at_emotion_slash_utils";
      packageName = "@emotion/utils";
      version = "0.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/utils/-/utils-0.11.3.tgz";
        sha512 = "0o4l6pZC+hI88+bzuaX/6BgOvQVhbt2PfmxauVaYOGgbsAw14wdKyvMCZXnsnsHys94iadcF+RG/wZyx6+ZZBw==";
      };
    };
    "@emotion/weak-memoize-0.2.5" = {
      name = "_at_emotion_slash_weak-memoize";
      packageName = "@emotion/weak-memoize";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/weak-memoize/-/weak-memoize-0.2.5.tgz";
        sha512 = "6U71C2Wp7r5XtFtQzYrW5iKFT67OixrSxjI4MptCHzdSVlgabczzqLe0ZSgnub/5Kp4hSbpDB1tMytZY9pwxxA==";
      };
    };
    "@types/parse-json-4.0.0" = {
      name = "_at_types_slash_parse-json";
      packageName = "@types/parse-json";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/parse-json/-/parse-json-4.0.0.tgz";
        sha512 = "//oorEZjL6sbPcKUaCdIGlIUeH26mgzimjBB77G6XRgnDl/L5wOnpyBGRe/Mmf5CVW3PwEBE1NjiMZ/ssFh4wA==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "babel-plugin-emotion-10.0.29" = {
      name = "babel-plugin-emotion";
      packageName = "babel-plugin-emotion";
      version = "10.0.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-emotion/-/babel-plugin-emotion-10.0.29.tgz";
        sha512 = "7Jpi1OCxjyz0k163lKtqP+LHMg5z3S6A7vMBfHnF06l2unmtsOmFDzZBpGf0CWo1G4m8UACfVcDJiSiRuu/cSw==";
      };
    };
    "babel-plugin-macros-2.8.0" = {
      name = "babel-plugin-macros";
      packageName = "babel-plugin-macros";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-macros/-/babel-plugin-macros-2.8.0.tgz";
        sha512 = "SEP5kJpfGYqYKpBrj5XU3ahw5p5GOHJ0U5ssOSQ/WBVdwkD2Dzlce95exQTs3jOVWPPKLBN2rlEWkCK7dSmLvg==";
      };
    };
    "babel-plugin-syntax-jsx-6.18.0" = {
      name = "babel-plugin-syntax-jsx";
      packageName = "babel-plugin-syntax-jsx";
      version = "6.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-syntax-jsx/-/babel-plugin-syntax-jsx-6.18.0.tgz";
        sha1 = "0af32a9a6e13ca7a3fd5069e62d7b0f58d0d8946";
      };
    };
    "callsites-3.1.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz";
        sha512 = "P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "classnames-2.2.6" = {
      name = "classnames";
      packageName = "classnames";
      version = "2.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/classnames/-/classnames-2.2.6.tgz";
        sha512 = "JR/iSQOSt+LQIWwrwEzJ9uk0xfN3mTVYMwt1Ir5mUcSN6pU+V4zQFFaJsclJbPuAUQH+yfWef6tm7l1quW3C8Q==";
      };
    };
    "clone-2.1.2" = {
      name = "clone";
      packageName = "clone";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-2.1.2.tgz";
        sha1 = "1b7f4b9f591f1e8f83670401600345a02887435f";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "convert-source-map-1.7.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.7.0.tgz";
        sha512 = "4FJkXzKXEDB1snCFZlLP4gpC3JILicCpGbzG9f9G7tGqGCzETQ2hWPrcinA9oU4wtf2biUaEH5065UnMeR33oA==";
      };
    };
    "cosmiconfig-6.0.0" = {
      name = "cosmiconfig";
      packageName = "cosmiconfig";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cosmiconfig/-/cosmiconfig-6.0.0.tgz";
        sha512 = "xb3ZL6+L8b9JLLCx3ZdoZy4+2ECphCMo2PwqgP1tlfVq6M6YReyzBJtvWWtbDSpNr9hn96pkCiZqUcFEc+54Qg==";
      };
    };
    "cross-spawn-4.0.2" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-4.0.2.tgz";
        sha1 = "7b9247621c23adfdd3856004a823cbe397424d41";
      };
    };
    "csstype-2.6.9" = {
      name = "csstype";
      packageName = "csstype";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-2.6.9.tgz";
        sha512 = "xz39Sb4+OaTsULgUERcCk+TJj8ylkL4aSVDQiX/ksxbELSqwkgt4d4RD7fovIdgJGSuNYqwZEiVjYY5l0ask+Q==";
      };
    };
    "deep-equal-1.1.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.1.1.tgz";
        sha512 = "yd9c5AdiqVcR+JjcwUQb9DkhJc8ngNr0MahEBGvDiJw8puWab2yZlh+nkasOnZP+EGTAP6rRp2JzJhJZzvNF8g==";
      };
    };
    "default-shell-1.0.1" = {
      name = "default-shell";
      packageName = "default-shell";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/default-shell/-/default-shell-1.0.1.tgz";
        sha1 = "752304bddc6174f49eb29cb988feea0b8813c8bc";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "dom-helpers-3.4.0" = {
      name = "dom-helpers";
      packageName = "dom-helpers";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-helpers/-/dom-helpers-3.4.0.tgz";
        sha512 = "LnuPJ+dwqKDIyotW1VzmOZ5TONUN7CwkCR5hrgawTUbkBGYdeoNLZo6nNfGkCrjtE1nXXaj7iMMpDa8/d9WoIA==";
      };
    };
    "electron-log-3.0.9" = {
      name = "electron-log";
      packageName = "electron-log";
      version = "3.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-log/-/electron-log-3.0.9.tgz";
        sha512 = "kfV4riUqW8uooYLAfrlB3EJW66W29ePipJU4/Fm8UxQekVNcR2qHI/0tiJX3oWM79VdAUiiYqL9V49lhnSIO8g==";
      };
    };
    "electron-settings-3.2.0" = {
      name = "electron-settings";
      packageName = "electron-settings";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-settings/-/electron-settings-3.2.0.tgz";
        sha512 = "7U+vDKd5Gch4Z9K6FjGq80eB3Anwz2GuPc2h/6hOiuvZrS1w+UNPcAA0oAU8G1s9sWAVEadCsr4ZJR6J4iTdzA==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "es-abstract-1.17.4" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.17.4.tgz";
        sha512 = "Ae3um/gb8F0mui/jPL+QiqmglkUsaQf7FwBEHYIFkztkneosu9imhqHpBzQ3h1vit8t5iQ74t6PEVvphBZiuiQ==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "execa-0.5.1" = {
      name = "execa";
      packageName = "execa";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-0.5.1.tgz";
        sha1 = "de3fb85cb8d6e91c85bcbceb164581785cb57b36";
      };
    };
    "find-root-1.1.0" = {
      name = "find-root";
      packageName = "find-root";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-root/-/find-root-1.1.0.tgz";
        sha512 = "NKfW6bec6GfKc0SGx1e07QZY9PE99u0Bft/0rzSD5k3sO/vwkVUpDUKVm5Gpp5Ue3YfShPFTX2070tDs5kB9Ng==";
      };
    };
    "fix-path-2.1.0" = {
      name = "fix-path";
      packageName = "fix-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fix-path/-/fix-path-2.1.0.tgz";
        sha1 = "72ece739de9af4bd63fd02da23e9a70c619b4c38";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-stream-2.3.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-2.3.1.tgz";
        sha1 = "5f38f93f346009666ee0150a054167f91bdd95de";
      };
    };
    "graceful-fs-4.2.3" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.3.tgz";
        sha512 = "a30VEBm4PEdx1dRB7MFK7BejejvCvBronbLjht+sHuGYj8PHs7M/5Z+rt5lw551vZ7yfTCj4Vuyy3mSJytDWRQ==";
      };
    };
    "gud-1.0.0" = {
      name = "gud";
      packageName = "gud";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gud/-/gud-1.0.0.tgz";
        sha512 = "zGEOVKFM5sVPPrYs7J5/hYEw2Pof8KCyOwyhG8sAF26mCAeUFAcYPu1mwB7hhpIP29zOIBaDqwuHdLp0jvZXjw==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-symbols-1.0.1" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.1.tgz";
        sha512 = "PLcsoqu++dmEIZB+6totNFKq/7Do+Z0u4oT0zKOJNl3lYK6vGwwu2hjHs+68OEZbTjiUE9bgOABXbP/GvrS0Kg==";
      };
    };
    "history-4.10.1" = {
      name = "history";
      packageName = "history";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/history/-/history-4.10.1.tgz";
        sha512 = "36nwAD620w12kuzPAsyINPWJqlNbij+hpK1k9XRloDtym8mxzGYl2c17LnV6IAGB2Dmg4tEa7G7DlawS0+qjew==";
      };
    };
    "hoist-non-react-statics-3.3.2" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.2.tgz";
        sha512 = "/gGivxi8JPKWNm/W0jSmzcMPpfpPLc3dY/6GxhX2hQ9iGj3aDfklV4ET7NjKpSinLpJ5vafa9iiGIEZg10SfBw==";
      };
    };
    "import-fresh-3.2.1" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-3.2.1.tgz";
        sha512 = "6e1q1cnWP2RXD9/keSkxHScg508CdXqXWgWBaETNhyuBFz+kUZlKboh+ISK+bU++DmbHimVBrOz/zzPe0sZ3sQ==";
      };
    };
    "invariant-2.2.4" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz";
        sha512 = "phJfQVBuaJM5raOpJjSfkiD6BpbCE4Ns//LaXl6wGYtUBY83nWS6Rf9tXm2e8VaK60JEjYldbPif/A2B1C2gNA==";
      };
    };
    "is-arguments-1.0.4" = {
      name = "is-arguments";
      packageName = "is-arguments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arguments/-/is-arguments-1.0.4.tgz";
        sha512 = "xPh0Rmt8NE65sNzvyUmWgI1tz3mKq74lGA0mL8LYZcoIzKOzDh6HmrYm3d18k60nHerC8A9Km8kYu87zfSFnLA==";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-callable-1.1.5" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.1.5.tgz";
        sha512 = "ESKv5sMCJB2jnHTWZ3O5itG+O128Hsus4K4Qh1h2/cgn2vbgnLSVqfV46AeJA9D5EeeLa9w81KUXMtn34zhX+Q==";
      };
    };
    "is-date-object-1.0.2" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.2.tgz";
        sha512 = "USlDT524woQ08aoZFzh3/Z6ch9Y/EWXEHQ/AaRN0SkKq4t2Jw2R2339tSXmwuVoY7LLlBCbOIlx2myP/L5zk0g==";
      };
    };
    "is-regex-1.0.5" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.0.5.tgz";
        sha512 = "vlKW17SNq44owv5AQR3Cq0bQPEb8+kF3UKZ2fiZNOWtztYE5i0CzCZxFDwO58qAOWtxdBRVO/V5Qin1wjCqFYQ==";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "is-symbol-1.0.3" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.3.tgz";
        sha512 = "OwijhaRSgqvhm/0ZdAcXNZt9lYdKFpcRDT5ULUuYXPoT794UNOdU+gpT6Rzo7b4V2HUl/op6GqY894AZwv9faQ==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "json-parse-better-errors-1.0.2" = {
      name = "json-parse-better-errors";
      packageName = "json-parse-better-errors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-better-errors/-/json-parse-better-errors-1.0.2.tgz";
        sha512 = "mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==";
      };
    };
    "jsonfile-4.0.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-4.0.0.tgz";
        sha1 = "8771aae0799b64076b76640fca058f9c10e33ecb";
      };
    };
    "lines-and-columns-1.1.6" = {
      name = "lines-and-columns";
      packageName = "lines-and-columns";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.1.6.tgz";
        sha1 = "1c00c743b433cd0a4e80758f7b64a57440d9ff00";
      };
    };
    "lodash-4.17.15" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz";
        sha512 = "8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==";
      };
    };
    "lodash.flatten-4.4.0" = {
      name = "lodash.flatten";
      packageName = "lodash.flatten";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.flatten/-/lodash.flatten-4.4.0.tgz";
        sha1 = "f31c22225a9632d2bbf8e4addbef240aa765a61f";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "lru-cache-4.1.5" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.5.tgz";
        sha512 = "sWZlbEP2OsHNkXrMl5GYk/jKk70MBng6UU4YI/qGDYbgf6YbP4EvmqISbXCoJiRKs+1bSpFHVgQxvJ17F2li5g==";
      };
    };
    "material-design-icons-3.0.1" = {
      name = "material-design-icons";
      packageName = "material-design-icons";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/material-design-icons/-/material-design-icons-3.0.1.tgz";
        sha1 = "9a71c48747218ebca51e51a66da682038cdcb7bf";
      };
    };
    "materialize-css-1.0.0" = {
      name = "materialize-css";
      packageName = "materialize-css";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/materialize-css/-/materialize-css-1.0.0.tgz";
        sha512 = "4/oecXl8y/1i8RDZvyvwAICyqwNoKU4or5uf8uoAd74k76KzZ0Llym4zhJ5lLNUskcqjO0AuMcvNyDkpz8Z6zw==";
      };
    };
    "mini-create-react-context-0.3.2" = {
      name = "mini-create-react-context";
      packageName = "mini-create-react-context";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mini-create-react-context/-/mini-create-react-context-0.3.2.tgz";
        sha512 = "2v+OeetEyliMt5VHMXsBhABoJ0/M4RCe7fatd/fBy6SMiKazUSEt3gxxypfnk2SHMkdBYvorHRoQxuGoiwbzAw==";
      };
    };
    "npm-run-path-2.0.2" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-2.0.2.tgz";
        sha1 = "35a9232dfa35d7067b4cb2ddf2357b1871536c5f";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-inspect-1.7.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.7.0.tgz";
        sha512 = "a7pEHdh1xKIAgTySUGgLMx/xwDZskN1Ud6egYYN3EdRW4ZMPNEDUTF+hwy2LUC+Bl+SyLXANnwz/jyh/qutKUw==";
      };
    };
    "object-is-1.0.2" = {
      name = "object-is";
      packageName = "object-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-is/-/object-is-1.0.2.tgz";
        sha512 = "Epah+btZd5wrrfjkJZq1AOB9O6OxUQto45hzFd7lXGrpHPGE0W1k+426yrZV+k6NJOzLNNW/nVsmZdIWsAqoOQ==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.0" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.0.tgz";
        sha512 = "exHJeq6kBKj58mqGyTQ9DFvrZC/eR6OwxzoM9YRoGBqrXYonaFyGiFMuc9VZrXf7DarreEwMpurG3dd+CNyW5w==";
      };
    };
    "p-finally-1.0.0" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha1 = "3fbcfb15b899a44123b34b6dcc18b724336a2cae";
      };
    };
    "parent-module-1.0.1" = {
      name = "parent-module";
      packageName = "parent-module";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parent-module/-/parent-module-1.0.1.tgz";
        sha512 = "GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
      };
    };
    "parse-json-5.0.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-5.0.0.tgz";
        sha512 = "OOY5b7PAEFV0E2Fir1KOkxchnZNCdowAJgQ5NuxjpBKTRP3pQhwkrkxqQjeoKJ+fO7bCpmIZaogI4eZGDMEGOw==";
      };
    };
    "path-key-2.0.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-2.0.1.tgz";
        sha1 = "411cadb574c5a140d3a4b1910d40d80cc9f40b40";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-to-regexp-1.8.0" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-1.8.0.tgz";
        sha512 = "n43JRhlUKUAlibEJhPeir1ncUID16QnEjNpwzNdO3Lm4ywrBpBZ5oLD0I6br9evr1Y9JTqwRtAh7JLoOzAQdVA==";
      };
    };
    "path-type-4.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-4.0.0.tgz";
        sha512 = "gDKb8aZMDeD/tZWs9P6+q0J9Mwkdl6xMV8TjnGP3qJVJ06bdMgkbBlLU8IdfOsIsFz2BW1rNVT3XuNEl8zPAvw==";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "promise-timeout-1.3.0" = {
      name = "promise-timeout";
      packageName = "promise-timeout";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise-timeout/-/promise-timeout-1.3.0.tgz";
        sha512 = "5yANTE0tmi5++POym6OgtFmwfDvOXABD9oj/jLQr5GPEyuNEb7jH4wbbANJceJid49jwhi1RddxnhnEAb/doqg==";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "react-16.13.0" = {
      name = "react";
      packageName = "react";
      version = "16.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.13.0.tgz";
        sha512 = "TSavZz2iSLkq5/oiE7gnFzmURKZMltmi193rm5HEoUDAXpzT9Kzw6oNZnGoai/4+fUnm7FqS5dwgUL34TujcWQ==";
      };
    };
    "react-dom-16.13.0" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.13.0.tgz";
        sha512 = "y09d2c4cG220DzdlFkPTnVvGTszVvNpC73v+AaLGLHbkpy3SSgvYq8x0rNwPJ/Rk/CicTNgk0hbHNw1gMEZAXg==";
      };
    };
    "react-is-16.13.0" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.0.tgz";
        sha512 = "GFMtL0vHkiBv9HluwNZTggSn/sCyEt9n02aM0dSAjGGyqyNlAyftYm4phPxdvCigG15JreC5biwxCgTAJZ7yAA==";
      };
    };
    "react-keyboard-event-handler-1.5.4" = {
      name = "react-keyboard-event-handler";
      packageName = "react-keyboard-event-handler";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-keyboard-event-handler/-/react-keyboard-event-handler-1.5.4.tgz";
        sha512 = "MSOxU/sQ5q9XWNHhXAJxzh4xVLZjKORGNC2Pzvx3qUo24TQeztGB0tq8oSArwX6vfKSIVijiw8wBmkN5pJOB4w==";
      };
    };
    "react-lifecycles-compat-3.0.4" = {
      name = "react-lifecycles-compat";
      packageName = "react-lifecycles-compat";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-lifecycles-compat/-/react-lifecycles-compat-3.0.4.tgz";
        sha512 = "fBASbA6LnOU9dOU2eW7aQ8xmYBSXUIWr+UmF9b1efZBazGNO+rcXT/icdKnYm2pTwcRylVUYwW7H1PHfLekVzA==";
      };
    };
    "react-materialize-2.6.0" = {
      name = "react-materialize";
      packageName = "react-materialize";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-materialize/-/react-materialize-2.6.0.tgz";
        sha512 = "bBxYogT/aX3WhBR9KJj6mhRTDIv3NFqnZbugShqjNC0cWc9BpeoCpLGxZ37/Rs2ca43IJBHapQIpZOUTQZM5ig==";
      };
    };
    "react-router-5.1.2" = {
      name = "react-router";
      packageName = "react-router";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router/-/react-router-5.1.2.tgz";
        sha512 = "yjEuMFy1ONK246B+rsa0cUam5OeAQ8pyclRDgpxuSCrAlJ1qN9uZ5IgyKC7gQg0w8OM50NXHEegPh/ks9YuR2A==";
      };
    };
    "react-router-dom-5.1.2" = {
      name = "react-router-dom";
      packageName = "react-router-dom";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router-dom/-/react-router-dom-5.1.2.tgz";
        sha512 = "7BPHAaIwWpZS074UKaw1FjVdZBSVWEk8IuDXdB+OkLb8vd/WRQIpA4ag9WQk61aEfQs47wHyjWUoUGGZxpQXew==";
      };
    };
    "react-transition-group-2.9.0" = {
      name = "react-transition-group";
      packageName = "react-transition-group";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-transition-group/-/react-transition-group-2.9.0.tgz";
        sha512 = "+HzNTCHpeQyl4MJ/bdE0u6XRMe9+XG/+aL4mCxVN4DnPBQ0/5bfHWPDuOZUzYdMj94daZaZdCCc1Dzt9R/xSSg==";
      };
    };
    "react-treebeard-3.2.4" = {
      name = "react-treebeard";
      packageName = "react-treebeard";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-treebeard/-/react-treebeard-3.2.4.tgz";
        sha512 = "TsvdUq2kbLavRXa8k4mmqfPse8HmSA9G9s1SZUtIpiYSccSwa0Tm6miMgx7DZ5gpKofQ+j/3Ua0rjsahM3/FQg==";
      };
    };
    "regenerator-runtime-0.13.4" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.4.tgz";
        sha512 = "plpwicqEzfEyTQohIKktWigcLzmNStMGwbOUbykx51/29Z3JOGYldaaNGK7ngNXV+UcoqvIMmloZ48Sr74sd+g==";
      };
    };
    "regexp.prototype.flags-1.3.0" = {
      name = "regexp.prototype.flags";
      packageName = "regexp.prototype.flags";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp.prototype.flags/-/regexp.prototype.flags-1.3.0.tgz";
        sha512 = "2+Q0C5g951OlYlJz6yu5/M33IcsESLlLfsyIaLJaG4FA2r4yP8MvVMJUUP/fVBkSpbbbZlS5gynbEWLipiiXiQ==";
      };
    };
    "resolve-1.15.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.15.1.tgz";
        sha512 = "84oo6ZTtoTUpjgNEr5SJyzQhzL72gaRodsSfyxC/AXRvwu0Yse9H8eF9IpGo7b8YetZhlI6v7ZQ6bKBFV/6S7w==";
      };
    };
    "resolve-from-4.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz";
        sha512 = "pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
      };
    };
    "resolve-pathname-3.0.0" = {
      name = "resolve-pathname";
      packageName = "resolve-pathname";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-pathname/-/resolve-pathname-3.0.0.tgz";
        sha512 = "C7rARubxI8bXFNB/hqcp/4iUeIXJhJZvFPFPiSPRnhU5UPxzMFIl+2E6yY6c4k9giDJAhtV+enfA+G89N6Csng==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "scheduler-0.19.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.19.0.tgz";
        sha512 = "xowbVaTPe9r7y7RUejcK73/j8tt2jfiyTednOvHbA8JoClvMYCp+r8QegLwK/n8zWQAtZb1fFnER4XLBZXrCxA==";
      };
    };
    "shallowequal-1.1.0" = {
      name = "shallowequal";
      packageName = "shallowequal";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shallowequal/-/shallowequal-1.1.0.tgz";
        sha512 = "y0m1JoUZSlPAjXVtPPW70aZWfIL/dSP7AFkRnniLCrK/8MDKog3TySTBmckD+RObVxH0v4Tox67+F14PdED2oQ==";
      };
    };
    "shell-env-0.3.0" = {
      name = "shell-env";
      packageName = "shell-env";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-env/-/shell-env-0.3.0.tgz";
        sha1 = "2250339022989165bda4eb7bf383afeaaa92dc34";
      };
    };
    "shell-path-2.1.0" = {
      name = "shell-path";
      packageName = "shell-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-path/-/shell-path-2.1.0.tgz";
        sha1 = "ea7d06ae1070874a1bac5c65bb9bdd62e4f67a38";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "string-replace-to-array-1.0.3" = {
      name = "string-replace-to-array";
      packageName = "string-replace-to-array";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-replace-to-array/-/string-replace-to-array-1.0.3.tgz";
        sha1 = "c93eba999a5ee24d731aebbaf5aba36b5f18f7bf";
      };
    };
    "string.prototype.trimleft-2.1.1" = {
      name = "string.prototype.trimleft";
      packageName = "string.prototype.trimleft";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimleft/-/string.prototype.trimleft-2.1.1.tgz";
        sha512 = "iu2AGd3PuP5Rp7x2kEZCrB2Nf41ehzh+goo8TV7z8/XDBbsvc6HQIlUl9RjkZ4oyrW1XM5UwlGl1oVEaDjg6Ag==";
      };
    };
    "string.prototype.trimright-2.1.1" = {
      name = "string.prototype.trimright";
      packageName = "string.prototype.trimright";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimright/-/string.prototype.trimright-2.1.1.tgz";
        sha512 = "qFvWL3/+QIgZXVmJBfpHmxLB7xsUXz6HsUmP8+5dRaC3Q7oKUv9Vo6aMCRZC1smrtyECFsIT30PqBJ1gTjAs+g==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "strip-eof-1.0.0" = {
      name = "strip-eof";
      packageName = "strip-eof";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-eof/-/strip-eof-1.0.0.tgz";
        sha1 = "bb43ff5598a6eb05d89b59fcd129c983313606bf";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "tiny-invariant-1.1.0" = {
      name = "tiny-invariant";
      packageName = "tiny-invariant";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-invariant/-/tiny-invariant-1.1.0.tgz";
        sha512 = "ytxQvrb1cPc9WBEI/HSeYYoGD0kWnGEOR8RY6KomWLBVhqz0RgTwVO9dLrGz7dC+nN9llyI7OKAgRq8Vq4ZBSw==";
      };
    };
    "tiny-warning-1.0.3" = {
      name = "tiny-warning";
      packageName = "tiny-warning";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-warning/-/tiny-warning-1.0.3.tgz";
        sha512 = "lBN9zLN/oAf68o3zNXYrdCt1kP8WsiGW8Oo2ka41b2IM5JL/S1CTyX1rW0mb/zSuJun0ZUrDxx4sqvYS2FWzPA==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha1 = "dc5e698cbd079265bc73e0377681a4e4e83f616e";
      };
    };
    "value-equal-1.0.1" = {
      name = "value-equal";
      packageName = "value-equal";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/value-equal/-/value-equal-1.0.1.tgz";
        sha512 = "NOJ6JZCAWr0zlxZt+xqCHNTEKOsrks2HQd4MqhP1qy4z1SkbEP467eNx6TgDKXMvUOb+OENfJCZwM+16n7fRfw==";
      };
    };
    "velocity-animate-1.5.2" = {
      name = "velocity-animate";
      packageName = "velocity-animate";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/velocity-animate/-/velocity-animate-1.5.2.tgz";
        sha512 = "m6EXlCAMetKztO1ppBhGU1/1MR3IiEevO6ESq6rcrSQ3Q77xYSW13jkfXW88o4xMrkXJhy/U7j4wFR/twMB0Eg==";
      };
    };
    "velocity-react-1.4.3" = {
      name = "velocity-react";
      packageName = "velocity-react";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/velocity-react/-/velocity-react-1.4.3.tgz";
        sha512 = "zvefGm85A88S3KdF9/dz5vqyFLAiwKYlXGYkHH2EbXl+CZUD1OT0a0aS1tkX/WXWTa/FUYqjBaAzAEFYuSobBQ==";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "yaml-1.7.2" = {
      name = "yaml";
      packageName = "yaml";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-1.7.2.tgz";
        sha512 = "qXROVp90sb83XtAoqE8bP9RwAkTTZbugRUTm5YeFCBfNRPEp2YzTeqWiz7m5OORHzEvrA/qcGS8hp/E+MMROYw==";
      };
    };
  };
in
{
  "gopass-ui-git://github.com/codecentric/gopass-ui.git" = nodeEnv.buildNodePackage {
    name = "gopass-ui";
    packageName = "gopass-ui";
    version = "0.6.0";
    src = fetchgit {
      url = "git://github.com/codecentric/gopass-ui.git";
      rev = "0c0a0a6a095e15eab618dff3a6c5e343fc50c39a";
      sha256 = "c9e4cacc69d806204c299a4bb07b4db90638f80f3a1a62fd1abd0e355a7bb1f1";
    };
    dependencies = [
      sources."@babel/code-frame-7.8.3"
      sources."@babel/helper-module-imports-7.8.3"
      sources."@babel/highlight-7.8.3"
      sources."@babel/runtime-7.8.7"
      sources."@babel/types-7.8.7"
      sources."@emotion/cache-10.0.29"
      sources."@emotion/core-10.0.28"
      sources."@emotion/css-10.0.27"
      sources."@emotion/hash-0.8.0"
      sources."@emotion/is-prop-valid-0.8.7"
      sources."@emotion/memoize-0.7.4"
      sources."@emotion/serialize-0.11.16"
      sources."@emotion/sheet-0.9.4"
      sources."@emotion/styled-10.0.27"
      sources."@emotion/styled-base-10.0.28"
      sources."@emotion/stylis-0.8.5"
      sources."@emotion/unitless-0.7.5"
      sources."@emotion/utils-0.11.3"
      sources."@emotion/weak-memoize-0.2.5"
      sources."@types/parse-json-4.0.0"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-3.2.1"
      sources."babel-plugin-emotion-10.0.29"
      sources."babel-plugin-macros-2.8.0"
      sources."babel-plugin-syntax-jsx-6.18.0"
      sources."callsites-3.1.0"
      sources."chalk-2.4.2"
      sources."classnames-2.2.6"
      sources."clone-2.1.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."convert-source-map-1.7.0"
      sources."cosmiconfig-6.0.0"
      sources."cross-spawn-4.0.2"
      sources."csstype-2.6.9"
      sources."deep-equal-1.1.1"
      sources."default-shell-1.0.1"
      sources."define-properties-1.1.3"
      sources."dom-helpers-3.4.0"
      sources."electron-log-3.0.9"
      sources."electron-settings-3.2.0"
      sources."error-ex-1.3.2"
      sources."es-abstract-1.17.4"
      sources."es-to-primitive-1.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."esutils-2.0.3"
      sources."execa-0.5.1"
      sources."find-root-1.1.0"
      sources."fix-path-2.1.0"
      sources."function-bind-1.1.1"
      sources."get-stream-2.3.1"
      sources."graceful-fs-4.2.3"
      sources."gud-1.0.0"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."has-symbols-1.0.1"
      sources."history-4.10.1"
      sources."hoist-non-react-statics-3.3.2"
      sources."import-fresh-3.2.1"
      sources."invariant-2.2.4"
      sources."is-arguments-1.0.4"
      sources."is-arrayish-0.2.1"
      sources."is-callable-1.1.5"
      sources."is-date-object-1.0.2"
      sources."is-regex-1.0.5"
      sources."is-stream-1.1.0"
      sources."is-symbol-1.0.3"
      sources."isarray-0.0.1"
      sources."isexe-2.0.0"
      sources."js-tokens-4.0.0"
      sources."json-parse-better-errors-1.0.2"
      sources."jsonfile-4.0.0"
      sources."lines-and-columns-1.1.6"
      sources."lodash-4.17.15"
      sources."lodash.flatten-4.4.0"
      sources."lodash.isstring-4.0.1"
      sources."loose-envify-1.4.0"
      sources."lru-cache-4.1.5"
      sources."material-design-icons-3.0.1"
      sources."materialize-css-1.0.0"
      sources."mini-create-react-context-0.3.2"
      sources."npm-run-path-2.0.2"
      sources."object-assign-4.1.1"
      sources."object-inspect-1.7.0"
      sources."object-is-1.0.2"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.0"
      sources."p-finally-1.0.0"
      sources."parent-module-1.0.1"
      sources."parse-json-5.0.0"
      sources."path-key-2.0.1"
      sources."path-parse-1.0.6"
      sources."path-to-regexp-1.8.0"
      sources."path-type-4.0.0"
      sources."pinkie-2.0.4"
      sources."pinkie-promise-2.0.1"
      sources."promise-timeout-1.3.0"
      sources."prop-types-15.7.2"
      sources."pseudomap-1.0.2"
      sources."react-16.13.0"
      sources."react-dom-16.13.0"
      sources."react-is-16.13.0"
      sources."react-keyboard-event-handler-1.5.4"
      sources."react-lifecycles-compat-3.0.4"
      sources."react-materialize-2.6.0"
      sources."react-router-5.1.2"
      sources."react-router-dom-5.1.2"
      sources."react-transition-group-2.9.0"
      sources."react-treebeard-3.2.4"
      sources."regenerator-runtime-0.13.4"
      sources."regexp.prototype.flags-1.3.0"
      sources."resolve-1.15.1"
      sources."resolve-from-4.0.0"
      sources."resolve-pathname-3.0.0"
      sources."safe-buffer-5.1.2"
      sources."scheduler-0.19.0"
      sources."shallowequal-1.1.0"
      sources."shell-env-0.3.0"
      sources."shell-path-2.1.0"
      sources."signal-exit-3.0.2"
      sources."source-map-0.5.7"
      sources."string-replace-to-array-1.0.3"
      sources."string.prototype.trimleft-2.1.1"
      sources."string.prototype.trimright-2.1.1"
      sources."strip-ansi-3.0.1"
      sources."strip-eof-1.0.0"
      sources."supports-color-5.5.0"
      sources."tiny-invariant-1.1.0"
      sources."tiny-warning-1.0.3"
      sources."to-fast-properties-2.0.0"
      sources."value-equal-1.0.1"
      sources."velocity-animate-1.5.2"
      sources."velocity-react-1.4.3"
      sources."which-1.3.1"
      sources."yallist-2.1.2"
      sources."yaml-1.7.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Awesome UI for the gopass CLI – a password manager for your daily business";
      homepage = https://github.com/codecentric/gopass-ui;
      license = "SEE LICENSE";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}